update eslint to require strict equality operators
6RiverSystems/srs-loopback-boilerplate pull request #3
Opened 2016-09-30 18:13 UTC by athieme

update package.json will newer versions of things we use

2016-09-30 18:31 UTC, jbcpollak approved these changes
some changes please

2016-09-30 18:31 UTC, jbcpollak commented on package.json
> +    "start": "NODE_ENV=development NODE_PATH=$NODE_PATH:./ nodemon .",
no - we are moving away from that, don't put this here

2016-09-30 18:31 UTC, jbcpollak commented on package.json
> +    "test:no-cover": "NODE_ENV=test NODE_PATH=$NODE_PATH:./ mocha",
same, also add ${MOCHA_OPTS} to the end of this line, and we should be specing the `test` directory too:

```
    "test": "NODE_ENV=test istanbul cover node_modules/.bin/_mocha -- ${MOCHA_OPTS} test",
    "test:no-cover": "NODE_ENV=test mocha test",
```

2016-09-30 18:31 UTC, jbcpollak commented on package.json
> +    "chai-as-promised": "^5.3.0",
this is a devDependency

2016-09-30 18:31 UTC, jbcpollak commented on package.json
> +		"loopback-component-bunyan": "git://github.com/6RiverSystems/loopback-component-bunyan.git#5917459",
I would prefer leaving this at a release version I think, but I dont feel too strongly about it - I consider the current commits experimental

2016-09-30 18:31 UTC, jbcpollak commented on package.json
> +    "es6-promisify": "^4.1.0",
I'm ok with this, but I left it out intentionally because it may or may not be needed, depending on usecase

2016-09-30 18:31 UTC, jbcpollak commented on package.json
> +		"eslint-config-defaults": "=9.0.0",
remove the `=` chars

2016-09-30 18:31 UTC, jbcpollak requested changes
some changes please

2016-09-30 19:09 UTC, athieme commented on package.json
> +    "start": "NODE_ENV=development NODE_PATH=$NODE_PATH:./ nodemon .",
done

2016-09-30 19:09 UTC, athieme commented on package.json
> +    "test:no-cover": "NODE_ENV=test NODE_PATH=$NODE_PATH:./ mocha",
done

2016-09-30 19:09 UTC, athieme commented on package.json
> +    "chai-as-promised": "^5.3.0",
done

2016-09-30 19:10 UTC, athieme commented on package.json
> +		"loopback-component-bunyan": "git://github.com/6RiverSystems/loopback-component-bunyan.git#5917459",
done

2016-09-30 19:10 UTC, athieme commented on package.json
> +		"eslint-config-defaults": "=9.0.0",
done

2016-09-30 19:14 UTC, jbcpollak requested changes
two small comments

2016-09-30 19:14 UTC, jbcpollak commented on package.json
>      "npm": "3.7.2"
I'd remove this line - we don't really care about npm version now that 3.x is standard.

2016-09-30 19:14 UTC, jbcpollak commented on package.json
> +    "loopback-connector-remote": "1.3.1",
this also isn't really necessary - its specifying a data store which may or may not be used by a new server. its like having `loopback-connector-postgres` (or mongo) listed

2017-02-21 19:25 UTC, jbcpollak commented
bailing on this

2017-02-21 19:25 UTC, closed without merging